### ISSUE TITLE
Routing issue with MapMvcAttributeRoutes & Prefixless Permalinks

### ISSUE THREAD

**Issue by TimoWillemsen** [PiranhaCMS/Piranha#399]
Hello,

I'm using MvcAttribute Routes combined with prefixless permalinks. For example I've got the following pages in Piranha:

/information/
/information/page1
/information/page2

Now I've created controllers, that add some more dynamic content the site, for example:

    public class TestController : Controller{
     [Route("information/more")]
     public ActionResult More(){
     //content here
     }
    }

However, I am getting a 404 whenever I try to access /information/more, I am able to access the PiranhaCMS pages. Do you have an idea how I can fix this?

NB. It works when I change the name of the route for example:

    public class TestController : Controller{
     [Route("information1/more")]
     public ActionResult More(){
     //content here
     }
    }

Then I can access /information1/more.

This is my routeconfig:

    routes.MapMvcAttributeRoutes();
    routes.MapRoute(
               name: "Default",
               url: "{controller}/{action}/{id}/{description}",
               defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional, description = UrlParameter.Optional },
               namespaces: new[] { "Project.Controllers" }
           ).DataTokens["UseNamespaceFallback"] = false;

**Comment by tidyui** [comment]
Hi there! There's a known issue with attribute routing that's fixed in the 2.2.5 version (the master-branch) which will be released #263.

**Comment by TimoWillemsen** [comment]
Hi! Thanks for the response. However I don't think it's the issue. I've changed it to protected (downloaded and recompiled), and I still get the same results. 

    The resource cannot be found.
    HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make    sure that it is spelled correctly.

    Requested URL: /page/testpage

/information/testpage

Routes to:
/page/testpage

**Comment by tidyui** [comment]
Hi again! I'm so sorry, I misunderstood your initial question a bit, but your second response clarifies it. The behaviour you're experiencing is the built in routing mechanism of the framework.

If you make a request for `/information/testpage` the HttpModule first scans permalinks for an exact match for **both** segments. If this isn't found the module scans permalinks for a match of the **first** segment, which will be found.

It then assumes you want to send the request to the route specified in the Page Type with the additional parameter as the action. In your case it will rewrite the request to `/page/testpage` where **page** is the default route, and **testpage** is assumed to be the action you want to execute.

This is simply so that you can create pages within the CMS, and post requests without loosing track of where you are. For example you might want to have a registration page in your sitemap with the url `/register`, but you might want to have additional actions in your controller like:

    /register/save
    /register/success
    /register/failure

This way, save, success & failure chooses the action that is executed, but the framework and menu still considers it being located at the main **register** page.

Regards

Håkan

**Comment by TimoWillemsen** [comment]
Hey Håkan,

Thanks a lot for your quick response! Hmm, that's what I figured. Is there a way I can make it work though? I'm mixing Piranha in an existing site, and I do not want to change the URLs for SEO purposes. 

Can I make it so, for example, that it checks for attribute routes first and then the piranha routing? I tried mixing up the order of the routing in my route config, but that doesn't seem to do anything.

TImo

**Comment by tidyui** [comment]
As PiranhaCMS is built as a HttpModule which intercepts the request on `BeginRequest` if will unfortunately always grab it before the MVC routing kicks in. If you want to keep Piranha CMS handling permalinks you can always take your existing Controller and let it inherit from Piranha.Mvc.SinglePageController:

    public class InformationController : SinglePageController 
    {
      // Let Piranha CMS handle the default route /information
      public ActionResult Index() {
        var model = GetModel();

        return View(model.GetView(), model);
      }

      // Custom action. /information/more
      public ActionResult More() {
        // Your custom action goes here.
      }
    }

If the routing is getting in your way you can always set Piranha to run in **passive mode** which will disable the permalink routing all together. But then new pages added into the manager won't be routed automatically without you handling it manually.

If you've already cloned the repo you could change the following to **always** break after matching permalinks to all segments in the request. 

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Web/Handlers/PermalinkHandler.cs#L51

You could also add a config parameter for something like `ExactPermalinkMatching` in the configuration and use this and send back a pull request :)

**Comment by TimoWillemsen** [comment]
Hi Håkan,

I'm trying to understand what's going on. Am I correct to assume something like this should work? I'll make it configurable and send a pull request :)

Instead of this code:

    for (int n = 0; n < args.Length; n++) {
     // Check if we can find a permalink in the current namespace
     perm = Permalink.GetByName(Config.SiteTreeNamespaceId, args.Subset(0, args.Length - n).Implode("/"));
     segments = args.Length - n;
     if (perm != null)
       break;
    }

Just this:

    perm = Permalink.GetByName(Config.SiteTreeNamespaceId, args.Subset(0, args.Length).Implode("/"));

**Comment by tidyui** [comment]
Yes! But when I think of it you shouldn't event need the `Subset` call since you're using the entire requested URL. So just the following should do:

    perm = Permalink.GetByName(Config.SiteTreeNamespaceId, args.Implode("/"));

Regards

**Comment by TimoWillemsen** [comment]
Ah yeah of course. Just copied it for trying out.

I'll make it configurable, and try to get it to you on github. It's not something I've ever done before :)

**Comment by tidyui** [comment]
Well it's never too late to get started :)

**Comment by TimoWillemsen** [comment]
I've tried a pull request, hopefully it's working :) Seemed pretty simple actually.
